import { Table, ScriptType } from '../types';

/**
 * Escape an identifier if needed (contains special chars or is lowercase with mixed case).
 * For simplicity, we don't quote unless the name contains spaces or special chars.
 */
function quoteIdent(name: string): string {
  if (/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(name)) return name;
  return `"${name}"`;
}

/**
 * Generate CREATE TABLE DDL + ALTER TABLE FK statements for a single table.
 */
export function generateTableDDL(table: Table, scriptType: ScriptType): string {
  if (scriptType === 'dbml') {
    return generateDBML(table);
  }
  return generateSQL(table, scriptType);
}

function generateSQL(table: Table, scriptType: ScriptType): string {
  const lines: string[] = [];
  const tableName = table.schema
    ? `${quoteIdent(table.schema)}.${quoteIdent(table.tableName)}`
    : quoteIdent(table.tableName);

  lines.push(`CREATE TABLE ${tableName} (`);

  // Columns
  const columnLines: string[] = [];
  for (const col of table.columns) {
    let line = `    ${quoteIdent(col.name)} ${col.type}`;
    if (col.nullable === 'No') {
      line += ' NOT NULL';
    }
    if (col.default != null && col.default !== '') {
      const defUpper = col.default.toUpperCase().trim();
      if (defUpper.startsWith('GENERATED')) {
        // Full IDENTITY clause preserved from parsing: GENERATED ... AS IDENTITY(...)
        line += ` ${col.default}`;
      } else if (defUpper === 'IDENTITY') {
        // Legacy parsed value — reconstruct proper syntax
        line += ' GENERATED BY DEFAULT AS IDENTITY';
      } else {
        line += ` DEFAULT ${col.default}`;
      }
    }
    columnLines.push(line);
  }

  // Inline constraints (PK, Unique — not FK)
  const inlineConstraints: string[] = [];
  for (const c of table.constraints) {
    if (c.type === 'Primary Key') {
      const name = c.name ? `CONSTRAINT ${quoteIdent(c.name)} ` : '';
      inlineConstraints.push(`    ${name}PRIMARY KEY (${c.localCols})`);
    } else if (c.type === 'Unique') {
      const name = c.name ? `CONSTRAINT ${quoteIdent(c.name)} ` : '';
      inlineConstraints.push(`    ${name}UNIQUE (${c.localCols})`);
    }
  }

  const allInnerLines = [...columnLines, ...inlineConstraints];
  lines.push(allInnerLines.join(',\n'));
  lines.push(');');

  // FK constraints as ALTER TABLE statements
  const fkConstraints = table.constraints.filter(c => c.type === 'Foreign Key');
  if (fkConstraints.length > 0) {
    lines.push('');
    for (const fk of fkConstraints) {
      const name = fk.name ? `CONSTRAINT ${quoteIdent(fk.name)} ` : '';
      lines.push(`ALTER TABLE ${tableName} ADD ${name}FOREIGN KEY (${fk.localCols}) REFERENCES ${fk.ref || ''};`);
    }
  }

  return lines.join('\n') + '\n';
}

function generateDBML(table: Table): string {
  const lines: string[] = [];
  const tableName = table.schema
    ? `${table.schema}.${table.tableName}`
    : table.tableName;

  lines.push(`Table ${tableName} {`);

  const pkCols = new Set<string>();
  const fkMap = new Map<string, string>(); // localCol -> ref
  const uniqueCols = new Set<string>();

  for (const c of table.constraints) {
    const cols = c.localCols.split(',').map(s => s.trim());
    if (c.type === 'Primary Key') {
      cols.forEach(col => pkCols.add(col.toUpperCase()));
    } else if (c.type === 'Foreign Key' && c.ref) {
      // For single-column FK, map to the ref
      if (cols.length === 1) {
        fkMap.set(cols[0].toUpperCase(), c.ref);
      }
    } else if (c.type === 'Unique') {
      cols.forEach(col => uniqueCols.add(col.toUpperCase()));
    }
  }

  for (const col of table.columns) {
    let line = `    ${col.name} ${col.type}`;
    const settings: string[] = [];
    if (col.nullable === 'No') settings.push('not null');
    if (pkCols.has(col.name.toUpperCase())) settings.push('pk');
    if (uniqueCols.has(col.name.toUpperCase())) settings.push('unique');
    if (col.default != null && col.default !== '') settings.push(`default: ${col.default}`);
    const ref = fkMap.get(col.name.toUpperCase());
    if (ref) {
      // Convert "schema.table(col)" to "> schema.table.col"
      const refMatch = ref.match(/^(.+?)\((.+?)\)$/);
      if (refMatch) {
        settings.push(`ref: > ${refMatch[1]}.${refMatch[2]}`);
      }
    }
    if (settings.length > 0) {
      line += ` [${settings.join(', ')}]`;
    }
    lines.push(line);
  }

  lines.push('}');
  return lines.join('\n') + '\n';
}

/**
 * Escape special regex characters in a string.
 */
function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Build a regex pattern that matches a table name, optionally with schema prefix.
 * Handles optional quoting (double quotes, backticks).
 */
function buildTableNamePattern(schema: string, tableName: string): string {
  const q = '["`]?'; // optional quote
  const namePattern = `${q}${escapeRegex(tableName)}${q}`;
  if (schema) {
    return `(?:${q}${escapeRegex(schema)}${q}\\.)?${namePattern}`;
  }
  return namePattern;
}

/**
 * Find the CREATE TABLE block boundaries for a specific table in rawContent.
 * Returns { start, end } indices or null if not found.
 */
function findCreateTableBlock(
  rawContent: string,
  table: Table,
  scriptType: ScriptType
): { start: number; end: number } | null {
  const tablePattern = buildTableNamePattern(table.schema, table.tableName);

  if (scriptType === 'dbml') {
    // DBML: Table schema.name { ... }
    const regex = new RegExp(
      `Table\\s+${tablePattern}\\s*(?:as\\s+\\w+\\s*)?\\{[\\s\\S]*?\\}`,
      'gi'
    );
    const match = regex.exec(rawContent);
    if (!match) return null;
    return { start: match.index, end: match.index + match[0].length };
  }

  // SQL: CREATE TABLE [IF NOT EXISTS] [schema.]name (...);
  const createRegex = new RegExp(
    `CREATE\\s+TABLE\\s+(?:IF\\s+NOT\\s+EXISTS\\s+)?${tablePattern}\\s*\\(`,
    'gi'
  );
  const match = createRegex.exec(rawContent);
  if (!match) return null;

  // Depth-match from the opening paren to find the closing paren
  const startPos = match.index;
  let openParenPos = match.index + match[0].length - 1; // position of '('
  let depth = 1;
  let pos = openParenPos + 1;

  while (depth > 0 && pos < rawContent.length) {
    if (rawContent[pos] === '(') depth++;
    else if (rawContent[pos] === ')') depth--;
    pos++;
  }

  // Now skip to the next semicolon
  while (pos < rawContent.length && rawContent[pos] !== ';') {
    pos++;
  }
  if (pos < rawContent.length) pos++; // include the semicolon

  return { start: startPos, end: pos };
}

/**
 * Find all ALTER TABLE ... FOREIGN KEY blocks for a specific table.
 * Returns an array of { start, end } sorted in reverse order (for safe replacement).
 */
function findAlterTableFKBlocks(
  rawContent: string,
  table: Table,
  scriptType: ScriptType
): { start: number; end: number }[] {
  if (scriptType === 'dbml') return []; // DBML doesn't use ALTER TABLE

  const tablePattern = buildTableNamePattern(table.schema, table.tableName);
  const regex = new RegExp(
    `ALTER\\s+TABLE\\s+(?:ONLY\\s+)?${tablePattern}\\s+ADD\\s+(?:CONSTRAINT\\s+[\\w"]+\\s+)?FOREIGN\\s+KEY\\s*\\([^)]*\\)\\s*REFERENCES\\s+[^;]*;`,
    'gi'
  );

  const blocks: { start: number; end: number }[] = [];
  let match;
  while ((match = regex.exec(rawContent)) !== null) {
    blocks.push({ start: match.index, end: match.index + match[0].length });
  }

  // Sort in reverse order so we can replace from end to start without offset issues
  blocks.sort((a, b) => b.start - a.start);
  return blocks;
}

/**
 * Replace a specific table's DDL block in the full script rawContent.
 * Finds and replaces the CREATE TABLE block and all ALTER TABLE FK blocks for the table.
 */
export function replaceTableDDL(
  rawContent: string,
  table: Table,
  newDDL: string,
  scriptType: ScriptType
): string {
  let content = rawContent;

  // First, remove all ALTER TABLE FK blocks for this table (reverse order for safe replacement)
  const fkBlocks = findAlterTableFKBlocks(content, table, scriptType);
  for (const block of fkBlocks) {
    // Remove the block and any trailing whitespace/newlines
    let endPos = block.end;
    while (endPos < content.length && (content[endPos] === '\n' || content[endPos] === '\r' || content[endPos] === ' ')) {
      endPos++;
    }
    content = content.substring(0, block.start) + content.substring(endPos);
  }

  // Then, replace the CREATE TABLE block
  const createBlock = findCreateTableBlock(content, table, scriptType);
  if (createBlock) {
    // Preserve leading whitespace/newlines before the block
    let endPos = createBlock.end;
    // Skip trailing whitespace after the block
    while (endPos < content.length && (content[endPos] === '\n' || content[endPos] === '\r' || content[endPos] === ' ')) {
      endPos++;
    }
    content = content.substring(0, createBlock.start) + newDDL.trim() + '\n\n' + content.substring(endPos);
  } else {
    // Table not found in rawContent — append the new DDL at the end
    content = content.trimEnd() + '\n\n' + newDDL.trim() + '\n';
  }

  return content;
}

// ── OMEGA format helpers ──────────────────────────────────────────────

export type TableInsertResult = { tableName: string; action: 'replaced' | 'inserted' };

interface OmegaBlock {
  tableName: string;
  fullText: string; // OMEGA header + CREATE TABLE statement (no trailing ALTER)
}

interface ParsedScript {
  preamble: string;
  createBlocks: OmegaBlock[];
  alterSection: string;
}

/**
 * Generate a 3-line OMEGA comment header for a table.
 */
export function generateOmegaHeader(tableName: string): string {
  const dashes = '-'.repeat(56);
  return `${dashes}\n--  DDL for Table ${tableName.toUpperCase()}\n${dashes}`;
}

/**
 * Extract the table name from a CREATE TABLE statement.
 * Handles schema-qualified and quoted names.
 */
function extractTableName(createStmt: string): string | null {
  const m = createStmt.match(
    /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:["`;]?(\w+)["`;]?\.)?["`;]?(\w+)["`;]?\s*\(/i
  );
  return m ? m[2] : null;
}

/**
 * Find the end of a CREATE TABLE block starting from the opening paren,
 * using paren-depth matching, then skipping to the semicolon.
 * Returns the index just past the semicolon (or end of string).
 */
function findCreateEnd(text: string, openParenPos: number): number {
  let depth = 1;
  let pos = openParenPos + 1;
  while (depth > 0 && pos < text.length) {
    if (text[pos] === '(') depth++;
    else if (text[pos] === ')') depth--;
    pos++;
  }
  // Skip to semicolon
  while (pos < text.length && text[pos] !== ';') pos++;
  if (pos < text.length) pos++; // include semicolon
  return pos;
}

/**
 * Decompose a full OMEGA-format script into preamble, CREATE TABLE blocks,
 * and a trailing ALTER TABLE section.
 */
export function parseScriptIntoBlocks(rawContent: string): ParsedScript {
  const blocks: OmegaBlock[] = [];
  let preamble = '';
  let alterSection = '';

  // Regex for OMEGA headers
  const omegaHeaderRe = /-{50,}\s*\n--\s+DDL\s+for\s+Table\s+(\w+)\s*\n-{50,}/gi;

  // Find all OMEGA headers and their positions
  const headers: { tableName: string; start: number; end: number }[] = [];
  let hm;
  while ((hm = omegaHeaderRe.exec(rawContent)) !== null) {
    headers.push({ tableName: hm[1], start: hm.index, end: hm.index + hm[0].length });
  }

  if (headers.length === 0) {
    // No OMEGA headers — try to find bare CREATE TABLE statements
    const createRe = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:["`;]?\w+["`;]?\.)?["`;]?\w+["`;]?\s*\(/gi;
    let cm;
    let firstCreateStart = -1;

    while ((cm = createRe.exec(rawContent)) !== null) {
      if (firstCreateStart === -1) firstCreateStart = cm.index;
      const openParen = cm.index + cm[0].length - 1;
      const end = findCreateEnd(rawContent, openParen);
      const createText = rawContent.substring(cm.index, end);
      const tName = extractTableName(createText);
      if (tName) {
        const header = generateOmegaHeader(tName);
        blocks.push({ tableName: tName.toUpperCase(), fullText: header + '\n\n' + createText.trim() });
      }
    }

    if (firstCreateStart > 0) {
      preamble = rawContent.substring(0, firstCreateStart).trim();
    }

    // Find alter section: first ALTER TABLE not inside a CREATE TABLE
    const alterIdx = findAlterSectionStart(rawContent, blocks);
    if (alterIdx >= 0) {
      alterSection = rawContent.substring(alterIdx).trim();
      // Remove any CREATE TABLE blocks text from alter section
      // (shouldn't happen, but defensive)
    }

    return { preamble, createBlocks: blocks, alterSection };
  }

  // Preamble is everything before the first header
  preamble = rawContent.substring(0, headers[0].start).trim();

  // Process each header: find the associated CREATE TABLE
  for (let i = 0; i < headers.length; i++) {
    const header = headers[i];
    const nextBoundary = i + 1 < headers.length ? headers[i + 1].start : rawContent.length;
    const regionAfterHeader = rawContent.substring(header.end, nextBoundary);

    // Find CREATE TABLE in this region
    const createMatch = regionAfterHeader.match(
      /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:["`;]?\w+["`;]?\.)?["`;]?\w+["`;]?\s*\(/i
    );

    if (createMatch && createMatch.index !== undefined) {
      const absCreateStart = header.end + createMatch.index;
      const openParen = absCreateStart + createMatch[0].length - 1;
      const absEnd = findCreateEnd(rawContent, openParen);
      const createText = rawContent.substring(absCreateStart, absEnd).trim();

      // Full block = OMEGA header + CREATE TABLE
      const omegaHeaderText = rawContent.substring(header.start, header.end);
      blocks.push({
        tableName: header.tableName.toUpperCase(),
        fullText: omegaHeaderText + '\n\n' + createText,
      });
    } else {
      // Header with no CREATE TABLE — keep it as-is
      const omegaHeaderText = rawContent.substring(header.start, header.end);
      blocks.push({
        tableName: header.tableName.toUpperCase(),
        fullText: omegaHeaderText,
      });
    }
  }

  // Find alter section: everything after the last CREATE TABLE block that starts with ALTER TABLE
  const alterIdx = findAlterSectionStart(rawContent, blocks);
  if (alterIdx >= 0) {
    alterSection = rawContent.substring(alterIdx).trim();
  }

  return { preamble, createBlocks: blocks, alterSection };
}

/**
 * Find the start of the ALTER TABLE section — the first ALTER TABLE statement
 * that is NOT inside a CREATE TABLE block. We look after all CREATE TABLE blocks.
 */
function findAlterSectionStart(rawContent: string, _blocks: OmegaBlock[]): number {
  // Find positions of all CREATE TABLE blocks to know where they end
  const createRe = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:["`;]?\w+["`;]?\.)?["`;]?\w+["`;]?\s*\(/gi;
  const createRanges: { start: number; end: number }[] = [];
  let cm;
  while ((cm = createRe.exec(rawContent)) !== null) {
    const openParen = cm.index + cm[0].length - 1;
    const end = findCreateEnd(rawContent, openParen);
    createRanges.push({ start: cm.index, end });
  }

  // Find all ALTER TABLE positions
  const alterRe = /ALTER\s+TABLE\s+/gi;
  let am;
  while ((am = alterRe.exec(rawContent)) !== null) {
    const pos = am.index;
    // Check if inside any CREATE TABLE range
    const insideCreate = createRanges.some(r => pos >= r.start && pos < r.end);
    if (!insideCreate) {
      return pos;
    }
  }
  return -1;
}

/**
 * Extract individual CREATE TABLE blocks from pasted DDL using paren-depth matching.
 * Preserves original formatting. Also extracts ALTER TABLE FK statements.
 */
function extractIncomingBlocks(incomingDDL: string): {
  creates: { tableName: string; text: string }[];
  alters: string[];
} {
  const creates: { tableName: string; text: string }[] = [];
  const alters: string[] = [];

  const createRe = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:["`;]?\w+["`;]?\.)?["`;]?\w+["`;]?\s*\(/gi;
  let cm;
  while ((cm = createRe.exec(incomingDDL)) !== null) {
    const openParen = cm.index + cm[0].length - 1;
    const end = findCreateEnd(incomingDDL, openParen);
    const text = incomingDDL.substring(cm.index, end).trim();
    const tName = extractTableName(text);
    if (tName) {
      creates.push({ tableName: tName.toUpperCase(), text });
    }
  }

  // Extract all ALTER TABLE statements (ADD CONSTRAINT, MODIFY, ADD column, etc.)
  const alterRe = /ALTER\s+TABLE\s+(?:ONLY\s+)?(?:["`;]?\w+["`;]?\.)?["`;]?\w+["`;]?\s+[^;]*;/gi;
  let am;
  while ((am = alterRe.exec(incomingDDL)) !== null) {
    // Skip if this ALTER TABLE is inside a CREATE TABLE block range
    const pos = am.index;
    const insideCreate = creates.some(c => {
      const cStart = incomingDDL.indexOf(c.text);
      return cStart >= 0 && pos >= cStart && pos < cStart + c.text.length;
    });
    if (!insideCreate) {
      alters.push(am[0].trim());
    }
  }

  return { creates, alters };
}

/**
 * Insert or replace multiple CREATE TABLE statements into an existing OMEGA-format script.
 * Returns the new script content and a results array for UI preview.
 */
export function insertOrReplaceMultipleTables(
  rawContent: string,
  incomingDDL: string
): { newContent: string; results: TableInsertResult[] } {
  const results: TableInsertResult[] = [];

  // Parse the existing script
  const parsed = parseScriptIntoBlocks(rawContent);

  // Extract incoming blocks
  const incoming = extractIncomingBlocks(incomingDDL);

  // Build a map of existing blocks (keyed by uppercase table name)
  const blockMap = new Map<string, OmegaBlock>();
  for (const block of parsed.createBlocks) {
    blockMap.set(block.tableName, block);
  }

  // Deduplicate incoming: last occurrence wins
  const incomingMap = new Map<string, string>();
  for (const c of incoming.creates) {
    incomingMap.set(c.tableName, c.text);
  }

  // Process each incoming table
  for (const [tableName, createText] of incomingMap) {
    const existing = blockMap.has(tableName);
    const header = generateOmegaHeader(tableName);
    blockMap.set(tableName, {
      tableName,
      fullText: header + '\n\n' + createText,
    });
    results.push({
      tableName,
      action: existing ? 'replaced' : 'inserted',
    });
  }

  // Sort all blocks A-Z by table name (case-insensitive)
  const sortedBlocks = Array.from(blockMap.values()).sort((a, b) =>
    a.tableName.localeCompare(b.tableName, undefined, { sensitivity: 'base' })
  );

  // Build alter section: keep existing alters, remove those for replaced tables, append new ones
  let alterLines = parsed.alterSection;

  // Remove ALL existing ALTER TABLE statements for replaced tables from the alter section
  const replacedTables = results.filter(r => r.action === 'replaced').map(r => r.tableName);
  for (const tName of replacedTables) {
    const pattern = new RegExp(
      `ALTER\\s+TABLE\\s+(?:ONLY\\s+)?(?:["'\`]?\\w+["'\`]?\\.)?["'\`]?${escapeRegex(tName)}["'\`]?\\s+[^;]*;\\s*`,
      'gi'
    );
    alterLines = alterLines.replace(pattern, '');
  }

  // Append incoming ALTER TABLE statements
  if (incoming.alters.length > 0) {
    const newAlters = incoming.alters.join('\n');
    alterLines = alterLines.trim();
    if (alterLines) {
      alterLines = alterLines + '\n' + newAlters;
    } else {
      alterLines = newAlters;
    }
  }

  // Reassemble
  const parts: string[] = [];
  if (parsed.preamble) {
    parts.push(parsed.preamble);
  }
  for (const block of sortedBlocks) {
    parts.push(block.fullText);
  }
  if (alterLines.trim()) {
    parts.push(alterLines.trim());
  }

  const newContent = parts.join('\n\n') + '\n';

  return { newContent, results };
}
