BEGIN;

-- 1. Redemption run: master + audit
CREATE TABLE IF NOT EXISTS iss.iss_sb_redemption_run (
    id                    bigint        NOT NULL GENERATED BY DEFAULT AS IDENTITY (START 150000000000001),
    uuid                  varchar(36)   DEFAULT gen_random_uuid(),
    run_no                numeric(2,0)  NOT NULL,
    process_date          timestamp     NOT NULL,
    status                varchar(50)   NOT NULL,
    warning_error_details jsonb,
    total_amount_accepted numeric(13,0),
    total_amount_redeemed numeric(13,0),
    version               numeric(5,0)  DEFAULT 1,
    is_deleted            varchar(1)    DEFAULT 'N',
    is_migrated           varchar(1)    DEFAULT 'N',
    created_dt            timestamp     DEFAULT CURRENT_TIMESTAMP,
    created_by            varchar(36)   NOT NULL,
    updated_dt            timestamp     DEFAULT CURRENT_TIMESTAMP,
    updated_by            varchar(36)   NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (uuid),
    UNIQUE (process_date, run_no)
);

CREATE TABLE IF NOT EXISTS iss.iss_sb_redemption_run_t (
    trans_id              bigint        NOT NULL GENERATED BY DEFAULT AS IDENTITY (START 150000000000001),
    trans_uuid            varchar(36)   DEFAULT gen_random_uuid(),
    id                    bigint        NOT NULL,
    uuid                  varchar(36)   NOT NULL REFERENCES iss.iss_sb_redemption_run(uuid),
    run_no                numeric(2,0)  NOT NULL,
    process_date          timestamp     NOT NULL,
    status                varchar(50)   NOT NULL,
    warning_error_details jsonb,
    total_amount_accepted numeric(13,0),
    total_amount_redeemed numeric(13,0),
    version               numeric(5,0)  NOT NULL,
    is_deleted            varchar(1)    NOT NULL,
    is_migrated           varchar(1)    NOT NULL,
    created_dt            timestamp     NOT NULL,
    created_by            varchar(36)   NOT NULL,
    updated_dt            timestamp     NOT NULL,
    updated_by            varchar(36)   NOT NULL,
    audit_action          varchar(1)    NOT NULL,
    audit_timestamp       timestamp     DEFAULT CURRENT_TIMESTAMP,
    is_history            varchar(1)    NOT NULL,
    PRIMARY KEY (trans_id),
    UNIQUE (trans_uuid)
);

-- 2. Redemption run summary: master + audit
CREATE TABLE IF NOT EXISTS iss.iss_sb_redemption_run_summary (
    id                         bigint        NOT NULL GENERATED BY DEFAULT AS IDENTITY (START 150000000000001),
    uuid                       varchar(36)   DEFAULT gen_random_uuid(),
    iss_sb_redemption_run_uuid varchar(36)   NOT NULL REFERENCES iss.iss_sb_redemption_run(uuid),
    iss_issuance_uuid          varchar(36)   NOT NULL,
    early_redemption_dt        timestamp     NOT NULL,
    total_redeemed_amount      numeric(13,0),
    total_outstanding_amount   numeric(13,0),
    version                    numeric(5,0)  DEFAULT 1,
    is_deleted                 varchar(1)    DEFAULT 'N',
    is_migrated                varchar(1)    DEFAULT 'N',
    created_dt                 timestamp     DEFAULT CURRENT_TIMESTAMP,
    created_by                 varchar(36)   NOT NULL,
    updated_dt                 timestamp     DEFAULT CURRENT_TIMESTAMP,
    updated_by                 varchar(36)   NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (uuid),
    UNIQUE (iss_sb_redemption_run_uuid, iss_issuance_uuid)
);

CREATE TABLE IF NOT EXISTS iss.iss_sb_redemption_run_summary_t (
    trans_id                   bigint        NOT NULL GENERATED BY DEFAULT AS IDENTITY (START 150000000000001),
    trans_uuid                 varchar(36)   DEFAULT gen_random_uuid(),
    id                         bigint        NOT NULL,
    uuid                       varchar(36)   NOT NULL REFERENCES iss.iss_sb_redemption_run_summary(uuid),
    iss_sb_redemption_run_uuid varchar(36)   NOT NULL,
    iss_issuance_uuid          varchar(36)   NOT NULL,
    early_redemption_dt        timestamp     NOT NULL,
    total_redeemed_amount      numeric(13,0),
    total_outstanding_amount   numeric(13,0),
    version                    numeric(5,0)  NOT NULL,
    is_deleted                 varchar(1)    NOT NULL,
    is_migrated                varchar(1)    NOT NULL,
    created_dt                 timestamp     NOT NULL,
    created_by                 varchar(36)   NOT NULL,
    updated_dt                 timestamp     NOT NULL,
    updated_by                 varchar(36)   NOT NULL,
    audit_action               varchar(1)    NOT NULL,
    audit_timestamp            timestamp     DEFAULT CURRENT_TIMESTAMP,
    is_history                 varchar(1)    NOT NULL,
    PRIMARY KEY (trans_id),
    UNIQUE (trans_uuid)
);

-- 3. Repoint iss_sb_redemption to the new redemption_run table.
ALTER TABLE iss.iss_sb_redemption   DROP CONSTRAINT IF EXISTS fk_sb_redemption_allotment_run;
ALTER TABLE iss.iss_sb_redemption   DROP COLUMN     IF EXISTS iss_sb_allotment_run_uuid;
ALTER TABLE iss.iss_sb_redemption_t DROP COLUMN     IF EXISTS iss_sb_allotment_run_uuid;

ALTER TABLE iss.iss_sb_redemption
    ADD COLUMN IF NOT EXISTS iss_sb_redemption_run_uuid varchar(36)
    REFERENCES iss.iss_sb_redemption_run(uuid);
ALTER TABLE iss.iss_sb_redemption_t
    ADD COLUMN IF NOT EXISTS iss_sb_redemption_run_uuid varchar(36);

-- 4. Drop submission_type from submission_group tables.
ALTER TABLE iss.iss_bid_submission_group         DROP COLUMN IF EXISTS submission_type;
ALTER TABLE iss.iss_bid_submission_group_t       DROP COLUMN IF EXISTS submission_type;
ALTER TABLE cm.cm_applicant_submission_group     DROP COLUMN IF EXISTS submission_type;
ALTER TABLE cm.cm_applicant_submission_group_t   DROP COLUMN IF EXISTS submission_type;

-- 5. Outstanding SGS (legacy ABA0024_OUTSTANDING_BOND).
--    bills_amount = T-Bills + CMTBs; sgs_md_amount = SGS (MD).
CREATE TABLE IF NOT EXISTS iss.iss_outstanding_sgs (
    id                 bigint        NOT NULL GENERATED BY DEFAULT AS IDENTITY (START 150000000000001),
    uuid               varchar(36)   DEFAULT gen_random_uuid(),
    year               varchar(4)    NOT NULL,
    month              varchar(2)    NOT NULL,
    bills_amount       numeric(13,0),
    sgs_md_amount      numeric(13,0),
    sgs_infra_amount   numeric(13,0),
    green_infra_amount numeric(13,0),
    version            numeric(5,0)  DEFAULT 1,
    is_deleted         varchar(1)    DEFAULT 'N',
    is_migrated        varchar(1)    DEFAULT 'Y',
    created_dt         timestamp     DEFAULT CURRENT_TIMESTAMP,
    created_by         varchar(36)   NOT NULL,
    updated_dt         timestamp     DEFAULT CURRENT_TIMESTAMP,
    updated_by         varchar(36)   NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (uuid),
    UNIQUE (year, month)
);

-- 6. Outstanding MAS Bills (legacy ABA0026_OUTSTANDING_MAS).
CREATE TABLE IF NOT EXISTS iss.iss_outstanding_mas (
    id              bigint        NOT NULL GENERATED BY DEFAULT AS IDENTITY (START 150000000000001),
    uuid            varchar(36)   DEFAULT gen_random_uuid(),
    year            varchar(4)    NOT NULL,
    month           varchar(2)    NOT NULL,
    week4_amount    numeric(13,0),
    week8_amount    numeric(13,0),
    week12_amount   numeric(13,0),
    week24_amount   numeric(13,0),
    week36_amount   numeric(13,0),
    other_amount    numeric(13,0),
    version         numeric(5,0)  DEFAULT 1,
    is_deleted      varchar(1)    DEFAULT 'N',
    is_migrated     varchar(1)    DEFAULT 'Y',
    created_dt      timestamp     DEFAULT CURRENT_TIMESTAMP,
    created_by      varchar(36)   NOT NULL,
    updated_dt      timestamp     DEFAULT CURRENT_TIMESTAMP,
    updated_by      varchar(36)   NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (uuid),
    UNIQUE (year, month)
);

-- 7. Investor type column + INVTYPE master codes.
ALTER TABLE iss.iss_bid_submission_group   ADD COLUMN IF NOT EXISTS investor_type varchar(50);
ALTER TABLE iss.iss_bid_submission_group_t ADD COLUMN IF NOT EXISTS investor_type varchar(50);

INSERT INTO cm.cm_master_code_category (id, uuid, category_description, is_editable, cate_code, version, is_deleted, is_migrated, created_dt, created_by, updated_dt, updated_by) VALUES (150000000000900, '31e8c924-f14b-4ec6-be97-1141b77ee900', 'Investor Type', 'Y', 'INVTYPE', 1, 'N', 'N', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM');
INSERT INTO cm.cm_master_code (id, uuid, master_code_key, mastercode_category_uuid, code_value, code_description, sequence_no, status, effective_from, version, is_editable, is_centrally_managed, is_deleted, is_migrated, created_dt, created_by, updated_dt, updated_by) VALUES (150000000000901, gen_random_uuid(), 'INVTYPE_INSTITUTIONAL', '31e8c924-f14b-4ec6-be97-1141b77ee900', 'INSTITUTIONAL', 'Institutional', 10, 'CMSTAT_ACTIVE', CURRENT_TIMESTAMP, 1, 'Y', 'N', 'N', 'N', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM');
INSERT INTO cm.cm_master_code (id, uuid, master_code_key, mastercode_category_uuid, code_value, code_description, sequence_no, status, effective_from, version, is_editable, is_centrally_managed, is_deleted, is_migrated, created_dt, created_by, updated_dt, updated_by) VALUES (150000000000902, gen_random_uuid(), 'INVTYPE_RETAIL',        '31e8c924-f14b-4ec6-be97-1141b77ee900', 'RETAIL',        'Retail',        20, 'CMSTAT_ACTIVE', CURRENT_TIMESTAMP, 1, 'Y', 'N', 'N', 'N', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM');

COMMIT;
